services:
  web:
    container_name: web
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    environment:
      - TZ=Europe/Berlin
    env_file:
      - ./app/.dev.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:17.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=complexpassword123
      - POSTGRES_DB=django
    ports:
      - "5432:5432"

volumes:
  postgres_data: